MCU = atmega16u2

BOOTLOADER = atmel-dfu

BOOTMAGIC_ENABLE = no
BLUETOOTH_ENABLE = no
CONSOLE_ENABLE = no
SLEEP_LED_ENABLE = no
MIDI_ENABLE = no		
AUDIO_ENABLE = no
BACKLIGHT_ENABLE = no
NKRO_ENABLE = no
UNICODE_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
RGBLIGHT_ENABLE = yes
VIA_ENABLE = yes
ENCODER_ENABLE = yes
LTO_ENABLE = yes
SPACE_CADET_ENABLE = no
COMBO_ENABLE = no
LEADER_ENABLE = no
CUSTOM_MATRIX = no
SPLIT_KEYBOARD = no